In [4]:
import pandas as pd

df = pd.read_json('Instagram_profile_scrapped.json')
df.head()

,inputUrl,id,username,url,fullName,biography,externalUrls,followersCount,followsCount,highlightReelCount,...,latestIgtvVideos,postsCount,latestPosts,fbid,externalUrl,externalUrlShimmed,businessAddress,error,errorDescription,requestErrorMessages
0,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"[{'id': '3892525615317028869', 'type': 'Image'...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.instagram.com/freetobemerescue/,2.994764e+09,freetobemerescue,https://www.instagram.com/freetobemerescue,Free To Be Me Rescue,Our goal is to never say no to a pet in need. ...,[],141.0,0.0,0.0,...,[],0.0,[],1.784140e+16,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.instagram.com/prefeituraangelica/,5.445798e+10,prefeituraangelica,https://www.instagram.com/prefeituraangelica,Prefeitura Municipal de Angélica,Secretarias:\n@sec.obras_angelicams \n@sec.sau...,"[{'title': '', 'lynx_url': 'https://l.instagra...",2192.0,15.0,0.0,...,[],352.0,"[{'id': '3926744355167488010', 'type': 'Video'...",1.784145e+16,http://angelica.ms.gov.br/,https://l.instagram.com/?u=http%3A%2F%2Fangeli...,NaN,NaN,NaN,NaN
3,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,"[{'type': 'Video', 'shortCode': 'C2p-X3NAIzs',...",3017.0,"[{'id': '3929682657824181389', 'type': 'Image'...",1.784141e+16,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN
4,https://www.instagram.com/everlastinghopeanimal/,5.395120e+10,everlastinghopeanimal,https://www.instagram.com/everlastinghopeanimal,Everlasting Hope Animal Rescue,,[],9.0,1.0,0.0,...,[],0.0,[],1.784145e+16,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# tried to use the following on Chrome search, but the result was not as CLEAN as expected
# site:instagram.com "animal shelter" "New York" -inurl:/p/ -inurl:/reel/
# therefore switched to asking Gemini to build a scrapper.

In [ ]:
# delete any column that have all Nan value
df.dropna(axis=1, how='all', inplace=True)
df.head()

,inputUrl,id,username,url,fullName,biography,externalUrls,followersCount,followsCount,highlightReelCount,...,latestIgtvVideos,postsCount,latestPosts,fbid,externalUrl,externalUrlShimmed,businessAddress,error,errorDescription,requestErrorMessages
0,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"[{'id': '3892525615317028869', 'type': 'Image'...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.instagram.com/freetobemerescue/,2.994764e+09,freetobemerescue,https://www.instagram.com/freetobemerescue,Free To Be Me Rescue,Our goal is to never say no to a pet in need. ...,[],141.0,0.0,0.0,...,[],0.0,[],1.784140e+16,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.instagram.com/prefeituraangelica/,5.445798e+10,prefeituraangelica,https://www.instagram.com/prefeituraangelica,Prefeitura Municipal de Angélica,Secretarias:\n@sec.obras_angelicams \n@sec.sau...,"[{'title': '', 'lynx_url': 'https://l.instagra...",2192.0,15.0,0.0,...,[],352.0,"[{'id': '3926744355167488010', 'type': 'Video'...",1.784145e+16,http://angelica.ms.gov.br/,https://l.instagram.com/?u=http%3A%2F%2Fangeli...,NaN,NaN,NaN,NaN
3,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,"[{'type': 'Video', 'shortCode': 'C2p-X3NAIzs',...",3017.0,"[{'id': '3929682657824181389', 'type': 'Image'...",1.784141e+16,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN
4,https://www.instagram.com/everlastinghopeanimal/,5.395120e+10,everlastinghopeanimal,https://www.instagram.com/everlastinghopeanimal,Everlasting Hope Animal Rescue,,[],9.0,1.0,0.0,...,[],0.0,[],1.784145e+16,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# explode the 'latestPosts' column so that each post gets its own row
df_flat = df.explode('latestPosts').reset_index(drop=True)
df_flat.head()

,inputUrl,id,username,url,fullName,biography,externalUrls,followersCount,followsCount,highlightReelCount,...,latestIgtvVideos,postsCount,latestPosts,fbid,externalUrl,externalUrlShimmed,businessAddress,error,errorDescription,requestErrorMessages
0,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"{'id': '3892525615317028869', 'type': 'Image',...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"{'id': '3816562994483311132', 'type': 'Image',...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"{'id': '3926870657690045934', 'type': 'Image',...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"{'id': '3918143241442581570', 'type': 'Image',...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.instagram.com/carolynforalbany/,5.730095e+10,carolynforalbany,https://www.instagram.com/carolynforalbany,"Carolyn McLeod - Albany City Councilor, Ward 2","Albany City Councilor, Ward 2.\nArmy veteran. ...",[],228.0,406.0,0.0,...,[],88.0,"{'id': '3909971449246002436', 'type': 'Image',...",1.784146e+16,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_flat['post_timestamp'] = df_flat['latestPosts'].apply(lambda x: x.get('timestamp') if isinstance(x, dict) else None)
df_flat['post_likes'] = df_flat['latestPosts'].apply(lambda x: x.get('likesCount') if isinstance(x, dict) else None)
df_flat['post_comments'] = df_flat['latestPosts'].apply(lambda x: x.get('commentsCount') if isinstance(x, dict) else None)

print(f"a total of {df_flat.shape[0]} posts")
df_flat[['username', 'followersCount', 'post_timestamp', 'post_likes']].head(10)

a total of 5551 posts

           username  followersCount            post_timestamp  post_likes
0  carolynforalbany           228.0  2026-05-08T13:00:22.000Z        13.0
1  carolynforalbany           228.0  2026-01-23T17:36:24.000Z         3.0
2  carolynforalbany           228.0  2026-06-24T22:18:06.000Z         1.0
3  carolynforalbany           228.0  2026-06-12T21:18:16.000Z         0.0
4  carolynforalbany           228.0  2026-06-01T14:42:22.000Z        11.0
5  carolynforalbany           228.0  2026-05-29T01:05:11.000Z        11.0
6  carolynforalbany           228.0  2026-05-21T23:53:08.000Z         4.0
7  carolynforalbany           228.0  2026-05-18T18:56:29.000Z         3.0
8  carolynforalbany           228.0  2026-05-03T20:22:26.000Z         7.0
9  carolynforalbany           228.0  2026-04-22T13:05:57.000Z        14.0

In [23]:
wrong_rows_count = len(df_flat[(df_flat['username'] == 'carolynforalbany') | (df_flat['username'] == 'prefeituraangelica')])
# print(f"'carolynforalbany' takes up to  {wrong_rows_count} rows")
df_flat = df_flat[(df_flat['username'] != 'carolynforalbany') & (df_flat['username'] != 'prefeituraangelica')]
df_flat[['username', 'followersCount', 'post_timestamp', 'post_likes']].head(10)

            username  followersCount            post_timestamp  post_likes
12  freetobemerescue           141.0                       NaN         NaN
25     rescuepupsinc           765.0  2026-06-28T19:25:00.000Z         4.0
26     rescuepupsinc           765.0  2026-06-27T12:08:27.000Z        10.0
27     rescuepupsinc           765.0  2026-06-27T00:32:12.000Z        13.0
28     rescuepupsinc           765.0  2026-06-26T16:33:54.000Z        13.0
29     rescuepupsinc           765.0  2026-06-26T12:31:05.000Z        16.0
30     rescuepupsinc           765.0  2026-06-25T19:41:20.000Z        15.0
31     rescuepupsinc           765.0  2026-06-24T20:47:44.000Z         7.0
32     rescuepupsinc           765.0  2026-06-23T19:54:56.000Z         9.0
33     rescuepupsinc           765.0  2026-06-23T11:00:44.000Z         8.0

In [24]:
# convert the 'post_timestamp' column to datetime and remove timezone information
df_flat['post_date'] = pd.to_datetime(df_flat['post_timestamp']).dt.tz_localize(None)
df_flat[['username', 'followersCount', 'post_timestamp', 'post_likes', 'post_date']].head(10)

,username,followersCount,post_timestamp,post_likes,post_date
12,freetobemerescue,141.0,NaN,NaN,NaT
25,rescuepupsinc,765.0,2026-06-28T19:25:00.000Z,4.0,2026-06-28 19:25:00
26,rescuepupsinc,765.0,2026-06-27T12:08:27.000Z,10.0,2026-06-27 12:08:27
27,rescuepupsinc,765.0,2026-06-27T00:32:12.000Z,13.0,2026-06-27 00:32:12
28,rescuepupsinc,765.0,2026-06-26T16:33:54.000Z,13.0,2026-06-26 16:33:54
29,rescuepupsinc,765.0,2026-06-26T12:31:05.000Z,16.0,2026-06-26 12:31:05
30,rescuepupsinc,765.0,2026-06-25T19:41:20.000Z,15.0,2026-06-25 19:41:20
31,rescuepupsinc,765.0,2026-06-24T20:47:44.000Z,7.0,2026-06-24 20:47:44
32,rescuepupsinc,765.0,2026-06-23T19:54:56.000Z,9.0,2026-06-23 19:54:56
33,rescuepupsinc,765.0,2026-06-23T11:00:44.000Z,8.0,2026-06-23 11:00:44

In [ ]:
# preview the first 10 rows of selected columns
preview_cols = ['username', 'followersCount', 'post_date', 'post_likes', 'post_comments', 'biography']

df_flat[preview_cols].head(10)

,username,followersCount,post_date,post_likes,post_comments,biography
12,freetobemerescue,141.0,NaT,NaN,NaN,Our goal is to never say no to a pet in need. ...
25,rescuepupsinc,765.0,2026-06-28 19:25:00,4.0,0.0,
26,rescuepupsinc,765.0,2026-06-27 12:08:27,10.0,0.0,
27,rescuepupsinc,765.0,2026-06-27 00:32:12,13.0,0.0,
28,rescuepupsinc,765.0,2026-06-26 16:33:54,13.0,0.0,
29,rescuepupsinc,765.0,2026-06-26 12:31:05,16.0,0.0,
30,rescuepupsinc,765.0,2026-06-25 19:41:20,15.0,0.0,
31,rescuepupsinc,765.0,2026-06-24 20:47:44,7.0,0.0,
32,rescuepupsinc,765.0,2026-06-23 19:54:56,9.0,1.0,
33,rescuepupsinc,765.0,2026-06-23 11:00:44,8.0,0.0,

In [ ]:
# 2. 聚合受众与互动指标（Engagement Matrix）： 用 groupby 同时抓出每个收容所的固定粉丝数（followersCount）、平均点赞数和平均评论数。 产出核心行销指标：平均受众参与度（Average ER, %）。 
# 3.然后可视化这些新data到一个表格上。maybe csv。

In [28]:
#1. 计算发帖频率（Consistency Score）： 用 groupby('username') 算出每个收容所最新帖子和最老帖子的时间差，除以帖子总数。 产出指标：平均每 X 天发一条帖。 
# date_range = df_flat.groupby('username')['post_date'].agg(['min', 'max', 'count'])
date_range = df_flat.groupby('username')['post_date'].agg(
    earliest_post = 'min', 
    latest_post = 'max', 
    total_post_count='count'
    ).reset_index()
date_range

,username,earliest_post,latest_post,total_post_count
0,10livesclub,2025-06-24 16:00:12,2026-06-28 19:00:36,12
1,10livesnyc,2026-06-17 21:50:18,2026-06-28 16:16:30,12
2,11thhourcanine,NaT,NaT,0
3,7heartsmaternityrescue,2026-06-02 16:26:17,2026-06-19 20:19:28,12
4,8acrek9andrehabilitation,NaT,NaT,0
...,...,...,...,...
562,wyoming_county_spca,2026-06-24 16:51:18,2026-06-28 19:05:07,12
563,yonkers.adoption.center,2023-10-16 23:58:28,2026-03-26 23:25:57,12
564,yorkie911rescue,2026-05-27 16:02:45,2026-06-26 22:55:00,12
565,zanisfurryfriends,2026-06-01 10:54:34,2026-06-26 11:35:22,12
566,zionsentus,2024-09-05 23:42:04,2026-06-27 16:03:22,12

In [33]:
df_flat.shape
df_flat.head()

,inputUrl,id,username,url,fullName,biography,externalUrls,followersCount,followsCount,highlightReelCount,...,externalUrl,externalUrlShimmed,businessAddress,error,errorDescription,requestErrorMessages,post_timestamp,post_likes,post_comments,post_date
12,https://www.instagram.com/freetobemerescue/,2.994764e+09,freetobemerescue,https://www.instagram.com/freetobemerescue,Free To Be Me Rescue,Our goal is to never say no to a pet in need. ...,[],141.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
25,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN,2026-06-28T19:25:00.000Z,4.0,0.0,2026-06-28 19:25:00
26,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN,2026-06-27T12:08:27.000Z,10.0,0.0,2026-06-27 12:08:27
27,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN,2026-06-27T00:32:12.000Z,13.0,0.0,2026-06-27 00:32:12
28,https://www.instagram.com/rescuepupsinc/,7.917638e+09,rescuepupsinc,https://www.instagram.com/rescuepupsinc,Rescue Pups Inc,,"[{'title': 'Rescue Pups', 'lynx_url': 'https:/...",765.0,11.0,0.0,...,http://www.rescuepups.org/,https://l.instagram.com/?u=http%3A%2F%2Fwww.re...,"{'city_name': 'Friendship, New York', 'city_id...",NaN,NaN,NaN,2026-06-26T16:33:54.000Z,13.0,0.0,2026-06-26 16:33:54

In [ ]:
df_flat['username'].value_counts().head(20)
# and there is where I realize i only caputured 12 post max per account😅💀 need to pivot.

username
rescuepupsinc                  12
peppertreerescue               12
nycatcoalition                 12
hudsonpawsdogrescue            12
chenangocountyspca             12
ttrrescue                      12
albany_humane_society          12
iph_ny                         12
heartofthecatskills            12
dogsindanger                   12
country.acres                  12
animalkindhudson               12
mohawkhumane                   12
cat.rescue.adoption.network    12
tipsandtails_tnr_rescue        12
brixiesrescue                  12
portlandgov                    12
pawsclawsprotectors            12
earthangelsrescue              12
northeast_pyr_rescue           12
Name: count, dtype: int64

In [40]:
# the time span of 12 posts for each account.
date_range['time_span_days'] = (date_range['latest_post'] - date_range['earliest_post']).dt.total_seconds() / (24 * 3600)
date_range

,username,earliest_post,latest_post,total_post_count,time_span_days
0,10livesclub,2025-06-24 16:00:12,2026-06-28 19:00:36,12,369.125278
1,10livesnyc,2026-06-17 21:50:18,2026-06-28 16:16:30,12,10.768194
2,11thhourcanine,NaT,NaT,0,NaN
3,7heartsmaternityrescue,2026-06-02 16:26:17,2026-06-19 20:19:28,12,17.161933
4,8acrek9andrehabilitation,NaT,NaT,0,NaN
...,...,...,...,...,...
562,wyoming_county_spca,2026-06-24 16:51:18,2026-06-28 19:05:07,12,4.092928
563,yonkers.adoption.center,2023-10-16 23:58:28,2026-03-26 23:25:57,12,891.977419
564,yorkie911rescue,2026-05-27 16:02:45,2026-06-26 22:55:00,12,30.286285
565,zanisfurryfriends,2026-06-01 10:54:34,2026-06-26 11:35:22,12,25.028333
566,zionsentus,2024-09-05 23:42:04,2026-06-27 16:03:22,12,659.681458

In [41]:
date_range.sort_values(by='time_span_days', ascending=True).head(20)

,username,earliest_post,latest_post,total_post_count,time_span_days
558,wicked.kittens,2024-09-24 19:01:02,2024-09-24 19:01:02,1,0.000000
333,northwindkennels,2014-10-23 18:05:30,2014-10-23 18:05:30,1,0.000000
180,fureverfriendswny,2020-09-11 00:04:38,2020-09-11 00:04:38,1,0.000000
316,new2urescues,2020-03-02 15:42:05,2020-03-02 15:42:05,1,0.000000
362,pawsacrossoswegocounty,2015-01-06 00:27:02,2015-01-06 00:37:19,2,0.007141
103,catassistance,2016-01-26 09:06:43,2016-01-26 09:29:22,12,0.015729
349,onelovepuppyrescue,2014-04-11 00:01:57,2014-04-11 00:25:40,12,0.016470
206,hearforadoption,2026-06-27 20:33:41,2026-06-28 12:02:09,12,0.644769
288,luckymeows,2013-10-29 03:01:56,2013-10-29 21:22:32,3,0.764306
547,wanderersrest,2025-07-08 17:20:10,2025-07-10 12:33:41,12,1.801053
90,buddysrescue,2026-06-26 20:00:01,2026-06-28 15:16:24,12,1.803044
38,animalleague,2026-06-26 20:03:36,2026-06-28 20:02:50,12,1.999468
320,newyorkbullycrew,2026-06-26 17:23:14,2026-06-28 18:56:01,12,2.064433
420,rescuedogsrocknyc,2026-06-26 12:20:59,2026-06-28 16:39:49,12,2.179745
260,kittenkornerrescue,2026-06-23 16:15:07,2026-06-26 00:10:08,12,2.329873
140,duffysfriends,2015-11-02 23:57:45,2015-11-05 14:09:49,12,2.591713
60,babylonanimalshelter,2026-06-26 00:00:15,2026-06-28 18:00:44,12,2.750336
366,pawscrossedny,2026-06-25 21:13:05,2026-06-28 17:42:43,12,2.853912
148,eriecountyspca,2026-06-25 18:01:28,2026-06-28 18:00:44,12,2.999491
344,oarwny,2026-06-25 11:06:40,2026-06-28 11:34:55,12,3.019618

In [ ]:
df_flat[df_flat['username']=="catassistance"].sort_values('post_date')
#  this filters the dataframe for posts by the user "catassistance" and sorts them by the post date. 
# This is where I realize somepoint in the scraping process, theuser "catassistance" 's data was not collected correctly which is why I am inspecting it here.
# there might be more users with the same issue. But it was difficult to separate what users were actually stopped posting a while ago from those whose data was not collected correctly during the scraping process.
# lesson: idk, just set reasonable expectation of what a data set can do.

,inputUrl,id,username,url,fullName,biography,externalUrls,followersCount,followsCount,highlightReelCount,...,externalUrl,externalUrlShimmed,businessAddress,error,errorDescription,requestErrorMessages,post_timestamp,post_likes,post_comments,post_date
5128,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:06:43.000Z,0.0,0.0,2016-01-26 09:06:43
5127,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:07:00.000Z,1.0,0.0,2016-01-26 09:07:00
5126,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:07:34.000Z,1.0,0.0,2016-01-26 09:07:34
5125,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:19:42.000Z,4.0,0.0,2016-01-26 09:19:42
5124,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:22:39.000Z,0.0,0.0,2016-01-26 09:22:39
5123,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:22:50.000Z,1.0,0.0,2016-01-26 09:22:50
5122,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:23:25.000Z,1.0,0.0,2016-01-26 09:23:25
5121,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:23:50.000Z,1.0,0.0,2016-01-26 09:23:50
5120,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:24:46.000Z,1.0,0.0,2016-01-26 09:24:46
5119,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:25:04.000Z,0.0,0.0,2016-01-26 09:25:04
5118,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:25:26.000Z,1.0,0.0,2016-01-26 09:25:26
5117,https://www.instagram.com/catassistance/,2.807927e+09,catassistance,https://www.instagram.com/catassistance,cat'assistance 🏄⛵,"Découvrez notre univers catamarans, paddles, k...","[{'title': '', 'lynx_url': 'https://l.instagra...",0.0,0.0,0.0,...,http://www.catassistance.com/,https://l.instagram.com/?u=http%3A%2F%2Fwww.ca...,NaN,NaN,NaN,NaN,2016-01-26T09:29:22.000Z,1.0,0.0,2016-01-26 09:29:22

In [43]:
df_flat.columns

Index(['inputUrl', 'id', 'username', 'url', 'fullName', 'biography',
       'externalUrls', 'followersCount', 'followsCount', 'highlightReelCount',
       'isBusinessAccount', 'joinedRecently', 'businessCategoryName',
       'private', 'verified', 'profilePicUrl', 'profilePicUrlHD',
       'igtvVideoCount', 'relatedProfiles', 'latestIgtvVideos', 'postsCount',
       'latestPosts', 'fbid', 'externalUrl', 'externalUrlShimmed',
       'businessAddress', 'error', 'errorDescription', 'requestErrorMessages',
       'post_timestamp', 'post_likes', 'post_comments', 'post_date'],
      dtype='str')

In [50]:
df_flat[df_flat['username']=="catassistance"][[
    'post_timestamp',
    'post_date',
]]

                post_timestamp           post_date
5117  2016-01-26T09:29:22.000Z 2016-01-26 09:29:22
5118  2016-01-26T09:25:26.000Z 2016-01-26 09:25:26
5119  2016-01-26T09:25:04.000Z 2016-01-26 09:25:04
5120  2016-01-26T09:24:46.000Z 2016-01-26 09:24:46
5121  2016-01-26T09:23:50.000Z 2016-01-26 09:23:50
5122  2016-01-26T09:23:25.000Z 2016-01-26 09:23:25
5123  2016-01-26T09:22:50.000Z 2016-01-26 09:22:50
5124  2016-01-26T09:22:39.000Z 2016-01-26 09:22:39
5125  2016-01-26T09:19:42.000Z 2016-01-26 09:19:42
5126  2016-01-26T09:07:34.000Z 2016-01-26 09:07:34
5127  2016-01-26T09:07:00.000Z 2016-01-26 09:07:00
5128  2016-01-26T09:06:43.000Z 2016-01-26 09:06:43

In [51]:
df_flat.groupby('username')['post_date'].max().dt.year.value_counts()

post_date
2026.0    376
2025.0     21
2024.0     17
2022.0      8
2023.0      7
2020.0      6
2018.0      5
2016.0      4
2013.0      4
2021.0      4
2019.0      3
2015.0      3
2014.0      3
2017.0      2
Name: count, dtype: int64

In [54]:
odd_accounts = (df_flat.groupby('username')['post_date'].max().dt.year.value_counts())
odd_accounts

post_date
2026.0    376
2025.0     21
2024.0     17
2022.0      8
2023.0      7
2020.0      6
2018.0      5
2016.0      4
2013.0      4
2021.0      4
2019.0      3
2015.0      3
2014.0      3
2017.0      2
Name: count, dtype: int64

In [ ]:
# During the data validation process, I identified potential data quality issues in the scraped Instagram dataset. For example, the account "catassistance" appears problematic because the latest captured post dates back to 2016, while manual inspection of the account page shows that it has continued posting recently. However, it is unclear whether this issue affects only a small number of accounts or whether some other accounts genuinely stopped posting years ago. The dataset shows that most accounts contain recent posts from 2025-2026, but a subset of accounts have much older latest post dates, which may represent either inactive accounts or incomplete scraping results. Therefore, the analysis will treat these older accounts cautiously rather than assuming all historical dates accurately represent current account activity. 
# One reason that I suspected was when posts were pinned, the scrapper might skip capturing the most recent posts because pinned posts can affect the order in which posts are retrieved. This could result in the latest post date in the dataset being older than the actual latest post date on the account page. But this doesn't appear to be the case.
#  我现在想要flag所有出现“catassistance”的情况，把健康数据和坏数据区分开。但我不懂的是有些账号可能就停留在了很久以前，但有些明明最近有新发帖，但没有scrape下来，这该怎么区分
#  idk如果加一个scraping 的AI guess vs 我自己manually check一些，做一个AI scrapping的Accuracy score，maybe a ConfusionMatrixDisplay？

In [59]:
print(df.columns.tolist())

['inputUrl', 'id', 'username', 'url', 'fullName', 'biography', 'externalUrls', 'followersCount', 'followsCount', 'highlightReelCount', 'isBusinessAccount', 'joinedRecently', 'businessCategoryName', 'private', 'verified', 'profilePicUrl', 'profilePicUrlHD', 'igtvVideoCount', 'relatedProfiles', 'latestIgtvVideos', 'postsCount', 'latestPosts', 'fbid', 'externalUrl', 'externalUrlShimmed', 'businessAddress', 'error', 'errorDescription', 'requestErrorMessages']

In [61]:
import numpy as np
df_flat['post_date'] = pd.to_datetime(df_flat['post_date'])

ig_profile_2 = df_flat.groupby('username').agg(
    nearest_post_date = ('post_date', 'max'),    # 最近的帖子日期
    earliest_post_date = ('post_date', 'min'),   # 最早的帖子日期
    total_number_of_posts = ('post_date', 'count'), # 最新捕获的帖子总数
    avg_likes=('post_likes', 'mean'),           # 近期平均点赞
    avg_comments=('post_comments', 'mean'),       # 近期平均评论
    followers_count=('followersCount', 'first')   # 粉丝基本盘
).reset_index()

In [63]:
ig_profile_2['captured_days_span'] = (ig_profile_2['nearest_post_date'] - ig_profile_2['earliest_post_date']).dt.days + 1

ig_profile_2['posting_frequency'] = ig_profile_2['captured_days_span'] / ig_profile_2['total_number_of_posts']

safe_line = pd.to_datetime('2025-01-01')
ig_profile_2['Is_Suspicious_Recency'] = ig_profile_2['nearest_post_date'] < safe_line

In [65]:
ig_profile_2['average_ER'] = ((ig_profile_2['avg_likes'] + ig_profile_2['avg_comments']) / (ig_profile_2['followers_count'] + 0.001)) * 100

# print(f"{ig_profile_2['average_ER'].mean()}")
print(f'{len(ig_profile_2)}')

567

In [72]:
suspicious_ones = ig_profile_2[ig_profile_2['Is_Suspicious_Recency'] == True]
print(f"成功拦截到最新发帖日期异常的账号共 {len(suspicious_ones)} 个：")
print(suspicious_ones['username'].tolist())

成功拦截到最新发帖日期异常的账号共 66 个：
['_cats_place', 'abcbassetrescue', 'adirondacksaveastray', 'all_paws_matter_animal_rescue_', 'animalsareforeverbklyn', 'arkofgraceministries', 'ateameliterescuedogs', 'barkstails', 'catassistance', 'cayugadogrescue', 'chenangocountyspca', 'citylackawanna', 'cozycats.ca', 'crabapplefarm_', 'delawarevalleyhumanesociety', 'duffysfriends', 'earthangelsrescue', 'evessanctuary', 'forgotten_felines_rescue', 'forourfriends', 'fourlegsgood', 'fredoniavetclinic', 'friends4poundpaws', 'friends_and_felines', 'fureverfriendswny', 'furrevercatandkitten', 'goldenpaw', 'gratefulgreyhounds', 'heartsofloverescue', 'herkimercountyhumane', 'hornell_animal_shelter', 'houseofpawsdogrescue', 'humanesocietybg', 'humanesocietylivingston', 'instagrambeagles', 'kaleidoscope_inc_', 'kitten_angels_', 'lewiscountyhumanesociety', 'lindas.cats', 'luckymeows', 'meadecanine', 'new2urescues', 'north.country.spca', 'northwindkennels', 'nycatpalace', 'nypeticare', 'onelovepuppyrescue', 'pause_4_paws.llc', 'paws_forthecause', 'pawsacrossoswegocounty', 'pineplains_ny', 'pipersdream', 'potsdamhumanesociety3199', 'precious.paws.bolingbrook', 'projectpaws', 'purringpawsrescueandadoption', 'salemanimalshelter', 'saveastrayuk', 'shelter.helper', 'shelter.share', 'spcaincattarauguscounty', 'the_spca_of_upstate_ny', 'triumphsmania', 'whiskers.inc', 'wicked.kittens', 'woodburyanimalshelter']

In [73]:
# 1. 筛选出最新帖子在2025年之后的健康账号
df_healthy = ig_profile_2[ig_profile_2['Is_Suspicious_Recency'] == False].copy()

# 2. 选择核心营销指标列
export_cols = ['username', 'followers_count', 'posting_frequency', 'average_ER', 'avg_likes', 'avg_comments']

# 3. 导出为 CSV 文件
df_healthy[export_cols].to_csv('NYS_Shelters_Healthy_Insta_Profiles.csv', index=False)

In [ ]:
df_healthy_real = df_healthy.dropna(subset=['posting_frequency'])

df_healthy_real[export_cols].to_csv(
    'NYS_Shelters_Healthy_real.csv',
    index=False
)

In [85]:
# 计算粉丝数与发帖频率的皮尔逊相关系数（接近-1或1代表强相关，接近0代表无相关）
does_fans_number_correlate_with_freq = df_healthy['followers_count'].corr(df_healthy['posting_frequency'])

print("fans number vs frequency correlation:", does_fans_number_correlate_with_freq)

fans number vs frequency correlation: -0.040021044879830506

In [82]:
# 计算发帖频率与平均互动率的相关系数
correlation_freq_er = df_healthy['posting_frequency'].corr(df_healthy['average_ER'])
print("发帖频率与互动率的相关系数:", correlation_freq_er)

发帖频率与互动率的相关系数: 0.06393268346087547

In [83]:
# 找出同时满足：发帖频率高于中位数 且 互动率高于中位数的账号
median_freq = df_healthy['posting_frequency'].median()
median_er = df_healthy['average_ER'].median()

# 筛选矩阵右上角（高频高ER）的明星账号
star_accounts = df_healthy[(df_healthy['posting_frequency'] <= median_freq) & (df_healthy['average_ER'] >= median_er)]
print("明星账号列表:")
print(star_accounts['username'].tolist())

明星账号列表:
['10livesnyc', '7heartsmaternityrescue', 'akronrescuecats', 'allstaranimalrescue', 'animalkindhudson', 'assv_shelter', 'befreegle_foundation', 'bethelsheltersrh', 'buffalopugrescue', 'camphappytailsnyc', 'care.of.dc', 'castasidetosurvive', 'cghsspca', 'cheektowagacsd', 'coveanimalrescue', 'daisys_promise_rescue', 'dcspca', 'flspca', 'frankiesfelinefund', 'habitatforcatsny', 'heartofthecatskills', 'heartsandbonesrescue', 'houstonbeaglerescue', 'hsyc_shelter', 'humanecnyrescue', 'k9orphans', 'lakeshorehumane', 'lakewood_kitten_rescue_', 'lancasteranimalslaco', 'lcsodogcontrol', 'logansrescue', 'luckysanimalrescue', 'mad_rescue_of_wny', 'nbarnj', 'northforkanimalwelfareleague', 'nycatwarriors', 'nycpawsomesquad', 'olliesangelsanimalrescue', 'oswegocountyspca', 'pawsafe', 'pawsinnthefalls', 'pawsitivechancerescue', 'pet_pride_of_new_york', 'pupstarzrescue', 'purrfectkittymission', 'rainorshinerescue', 'recycleabull', 'rescuepupsinc', 'rocdogofficial', 'rocknrescue_', 'saveapetanimalrescue', 'schenectadypolice', 'secondhanddogrescue', 'southamptonanimalshelteradopt', 'spcawestchester', 'specialneedsseniordogsanctuary', 'strayhavenspcawaverly', 'thegoodlifedogrescuenyc', 'thepawmission', 'tipsandtails_tnr_rescue', 'tnrtaskforce', 'tohanimalshelter', 'townofdovernj', 'townofwallkillpolice', 'trilakeshumanesociety', 'ucspca', 'waywardpaws', 'whiskers_agogo', 'yorkie911rescue']

In [86]:
print(df_healthy_real['followers_count'].sort_values(ascending=False))

223    6197187.0
70      651029.0
54      482927.0
320     282073.0
156     235918.0
         ...
135         60.0
490         59.0
387         24.0
152         24.0
404         18.0
Name: followers_count, Length: 397, dtype: float64

In [87]:
print(df_healthy_real['posting_frequency'].sort_values(ascending=False))

356    267.666667
192    153.666667
380    140.916667
124    131.833333
82     120.416667
          ...
320      0.250000
547      0.166667
38       0.166667
90       0.166667
206      0.083333
Name: posting_frequency, Length: 397, dtype: float64

In [90]:
print(df.columns)

Index(['inputUrl', 'id', 'username', 'url', 'fullName', 'biography',
       'externalUrls', 'followersCount', 'followsCount', 'highlightReelCount',
       'isBusinessAccount', 'joinedRecently', 'businessCategoryName',
       'private', 'verified', 'profilePicUrl', 'profilePicUrlHD',
       'igtvVideoCount', 'relatedProfiles', 'latestIgtvVideos', 'postsCount',
       'latestPosts', 'fbid', 'externalUrl', 'externalUrlShimmed',
       'businessAddress', 'error', 'errorDescription', 'requestErrorMessages'],
      dtype='str')

In [ ]:
# 在datawrapper画图时发现两个random的账号，不是shelter
# houstonbeaglerescue,1529.0,0.9166666666666666,1.6623054312369097,24.583333333333332,0.8333333333333334
# houstonrockets,6197187.0,1.9166666666666667,0.19338074943894482,11803.083333333334,181.08333333333334

# 一个private account,somehow还被包含在数据里还是发帖频率最高的 wtf
# p3tlif3shelter.inc

# 不是纽约州的
# racc_shelter	57200.0	0.5	0.9	490.9	6.6

# 已经不发帖了，曾经发的很频繁
# purrfectkittymission	18.0	1.4	13.6	2.3	0.2



accounts_to_remove = [
    "houstonbeaglerescue",
    "houstonrockets",
    "p3tlif3shelter.inc"
]

df_healthy_real = df_healthy_real[
    ~df_healthy_real["username"].isin(accounts_to_remove)
]

df_healthy_real[export_cols].to_csv(
    'NYS_Shelters_Healthy_real_1.csv',
    index=False
)

In [93]:
# 找出同时满足：发帖频率高于中位数 且 互动率高于中位数的账号
median_freq = df_healthy['posting_frequency'].median()
median_er = df_healthy['average_ER'].median()

# 筛选矩阵右上角（高频高ER）的明星账号
star_accounts = df_healthy[(df_healthy['posting_frequency'] <= median_freq) & (df_healthy['average_ER'] >= median_er)]
print("明星账号列表:")
print(star_accounts['username'].tolist())

明星账号列表:
['10livesnyc', '7heartsmaternityrescue', 'akronrescuecats', 'allstaranimalrescue', 'animalkindhudson', 'assv_shelter', 'befreegle_foundation', 'bethelsheltersrh', 'buffalopugrescue', 'camphappytailsnyc', 'care.of.dc', 'castasidetosurvive', 'cghsspca', 'cheektowagacsd', 'coveanimalrescue', 'daisys_promise_rescue', 'dcspca', 'flspca', 'frankiesfelinefund', 'habitatforcatsny', 'heartofthecatskills', 'heartsandbonesrescue', 'houstonbeaglerescue', 'hsyc_shelter', 'humanecnyrescue', 'k9orphans', 'lakeshorehumane', 'lakewood_kitten_rescue_', 'lancasteranimalslaco', 'lcsodogcontrol', 'logansrescue', 'luckysanimalrescue', 'mad_rescue_of_wny', 'nbarnj', 'northforkanimalwelfareleague', 'nycatwarriors', 'nycpawsomesquad', 'olliesangelsanimalrescue', 'oswegocountyspca', 'pawsafe', 'pawsinnthefalls', 'pawsitivechancerescue', 'pet_pride_of_new_york', 'pupstarzrescue', 'purrfectkittymission', 'rainorshinerescue', 'recycleabull', 'rescuepupsinc', 'rocdogofficial', 'rocknrescue_', 'saveapetanimalrescue', 'schenectadypolice', 'secondhanddogrescue', 'southamptonanimalshelteradopt', 'spcawestchester', 'specialneedsseniordogsanctuary', 'strayhavenspcawaverly', 'thegoodlifedogrescuenyc', 'thepawmission', 'tipsandtails_tnr_rescue', 'tnrtaskforce', 'tohanimalshelter', 'townofdovernj', 'townofwallkillpolice', 'trilakeshumanesociety', 'ucspca', 'waywardpaws', 'whiskers_agogo', 'yorkie911rescue']

In [94]:
print(f'posting frequency mean is: {df_healthy_real["posting_frequency"].mean():.2f}')
print(f'posting frequency median is: {df_healthy_real["posting_frequency"].median():.2f}')
# The median posting frequency among active NYS animal shelters is 5.08 days per post, 
# indicating that a typical organization updates their Instagram about once a week.
# However, the mean is skewed to 18.73 days per post due to a long tail of inactive or highly irregular accounts.

posting frequency mean is: 18.18
posting frequency median is: 5.12